# k-nearest neighbor

The k-Nearest Neighbors algorithm or KNN for short is a very simple technique.

The entire training dataset is stored. When a prediction is required, the k-most similar records to a new record from the training dataset are then located. From these neighbors, a summarized prediction is made.

Similarity between records can be measured many different ways. A problem or data-specific method can be used. Generally, with tabular data, a good starting point is the Euclidean distance.

Once the neighbors are discovered, the summary prediction can be made by returning the most common outcome or taking the average. As such, KNN can be used for classification or regression problems.

There is no model to speak of other than holding the entire training dataset. Because no work is done until a prediction is required, KNN is often referred to as a lazy learning method.

k-Nearest Neighbors (in 3 easy steps)
First we will develop each piece of the algorithm in this section, then we will tie all of the elements together into a working implementation applied to a real dataset in the next section.

 ### k-Nearest Neighbors tutorial is broken down into 3 parts:

## Step 1: Calculate Euclidean Distance.

## Step 2: Get Nearest Neighbors.

## Step 3: Make Predictions.

These steps will teach you the fundamentals of implementing and applying the k-Nearest Neighbors algorithm for classification and regression predictive modeling problems.


## Step 1: Calculate Euclidean Distance
The first step is to calculate the distance between two rows in a dataset.

Rows of data are mostly made up of numbers and an easy way to calculate the distance between two rows or vectors of numbers is to draw a straight line. This makes sense in 2D or 3D and scales nicely to higher dimensions.

We can calculate the straight line distance between two vectors using the Euclidean distance measure. It is calculated as the square root of the sum of the squared differences between the two vectors.

Euclidean Distance = sqrt(sum i to N (x1_i – x2_i)^2)
Where x1 is the first row of data, x2 is the second row of data and i is the index to a specific column as we sum across all columns.

With Euclidean distance, the smaller the value, the more similar two records will be. A value of 0 means that there is no difference between two records.

In [1]:
import random 
import numpy as np

In [2]:
def euclidean_distance(row1, row2):
    distance=0.0
    for i in range(len(row1)):
        distance+=(row1[i]-row2[i])**2
    return np.sqrt(distance)

In [22]:
dataset = [[2.7810836,2.550537003,0],
[1.465489372,2.362125076,0],
[3.396561688,4.400293529,0],
[1.38807019,1.850220317,0],
[3.06407232,3.005305973,0],
[7.627531214,2.759262235,1],
[5.332441248,2.088626775,1],
[6.922596716,1.77106367,1],
[8.675418651,-0.242068655,1],
[7.673756466,3.508563011,1]]

In [26]:
row0=dataset[0]
for row in dataset:
    distance=euclidean_distance(row0,row)
    print(distance)

0.0
1.3290173915275787
1.9494646655653247
1.5591439385540549
0.5356280721938492
4.952940611164215
2.7789902674782985
4.3312480380207
6.59862349695304
5.084885603993178


## Step 2: Get Nearest Neighbors
Neighbors for a new piece of data in the dataset are the k closest instances, as defined by our distance measure.

To locate the neighbors for a new piece of data within a dataset we must first calculate the distance between each record in the dataset to the new piece of data. We can do this using our distance function prepared above.

Once distances are calculated, we must sort all of the records in the training dataset by their distance to the new data. We can then select the top k to return as the most similar neighbors.

We can do this by keeping track of the distance for each record in the dataset as a tuple, sort the list of tuples by the distance (in descending order) and then retrieve the neighbors.

Below is a function named get_neighbors() that implements this.

In [27]:
def get_neighbors(train, test_row, num_neighbors):
    distances=list()
    for train_row in train:
        dist=euclidean_distance(test_row,train_row)
        distances.append((train_row,dist))
    distances.sort(key=lambda tup: tup[1])
    neighbors=list()
    for i in range(num_neighbors):
        neighbors.append(distances[i][0])
    return neighbors

In [61]:
neighbors = get_neighbors(dataset, dataset[0], 3)
for neighbor in neighbors:
    print(neighbor)

[2.7810836, 2.550537003, 0]
[3.06407232, 3.005305973, 0]
[1.465489372, 2.362125076, 0]


# Step 3: Make Predictions
The most similar neighbors collected from the training dataset can be used to make predictions.

In the case of classification, we can return the most represented class among the neighbors.

We can achieve this by performing the max() function on the list of output values from the neighbors. Given a list of class values observed in the neighbors, the max() function takes a set of unique class values and calls the count on the list of class values for each class value in the set.

Below is the function named predict_classification() that implements this

In [83]:
def predict_classification(train, test_row, num_neighbors):
    neighbors = get_neighbors(train, test_row, num_neighbors)
    output_values = [row[-1] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction

In [84]:
prediction = predict_classification(dataset, dataset[0], 3)
print('Expected %d, Got %d.' % (dataset[0][-1], prediction))

Expected 0, Got 0.


# iris flower

In [90]:
# # Make Predictions with k-nearest neighbors on the Iris Flowers Dataset
from csv import reader
from math import sqrt
# Load a CSV file
def load_csv(filename):
	dataset = list()
	with open(filename, 'r') as file:
		csv_reader = reader(file)
		for row in csv_reader:
			if not row:
				continue
			dataset.append(row)
	return dataset

In [91]:
# Convert string column to float
def str_column_to_float(dataset, column):
	for row in dataset:
		row[column] = float(row[column].strip())
# Convert string column to integer
def str_column_to_int(dataset, column):
	class_values = [row[column] for row in dataset]
	unique = set(class_values)
	lookup = dict()
	for i, value in enumerate(unique):
		lookup[value] = i
		print('[%s] => %d' % (value, i))
	for row in dataset:
		row[column] = lookup[row[column]]
	return lookup

In [92]:
# Find the min and max values for each column
def dataset_minmax(dataset):
	minmax = list()
	for i in range(len(dataset[0])):
		col_values = [row[i] for row in dataset]
		value_min = min(col_values)
		value_max = max(col_values)
		minmax.append([value_min, value_max])
	return minmax

In [97]:
# Rescale dataset columns to the range 0-1
# def normalize_dataset(dataset, minmax):
# 	for row in dataset:
# 		for i in range(len(row)):
# 			row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])

# Calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
	distance = 0.0
	for i in range(len(row1)-1):
		distance += (row1[i] - row2[i])**2
	return sqrt(distance)

In [98]:
# Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
	distances = list()
	for train_row in train:
		dist = euclidean_distance(test_row, train_row)
		distances.append((train_row, dist))
	distances.sort(key=lambda tup: tup[1])
	neighbors = list()
	for i in range(num_neighbors):
		neighbors.append(distances[i][0])
	return neighbors

In [99]:
# # Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
	neighbors = get_neighbors(train, test_row, num_neighbors)
	output_values = [row[-1] for row in neighbors]
	prediction = max(set(output_values), key=output_values.count)
	return prediction


In [121]:
# # Make a prediction with KNN on Iris Dataset
filename = './iris.csv'
dataset = load_csv(filename)
for i in range(len(dataset[0])-1):
	str_column_to_float(dataset, i)
# # convert class column to integers
str_column_to_int(dataset, len(dataset[0])-1)
# # # define model parameter
num_neighbors = 5
# # # define a new record
row = [5.7,2.9,4.2,1.3]
# # # predict the label
# label = predict_classification(dataset, row, num_neighbors)
# print('Data=%s, Predicted: %s' % (row, label))

[Iris-virginica] => 0
[Iris-versicolor] => 1
[Iris-setosa] => 2


# k-means 

In [1]:
# Importing libraries

import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split

from scipy.stats import mode

from sklearn.neighbors import KNeighborsClassifier

In [ ]:

# K Nearest Neighbors Classification

class K_Nearest_Neighbors_Classifier() :
	
	def __init__( self, K ) :
		
		self.K = K
		
	# Function to store training set
		
	def fit( self, X_train, Y_train ) :
		
		self.X_train = X_train
		
		self.Y_train = Y_train
		
		# no_of_training_examples, no_of_features
		
		self.m, self.n = X_train.shape
	
	# Function for prediction
		
	def predict( self, X_test ) :
		
		self.X_test = X_test
		
		# no_of_test_examples, no_of_features
		
		self.m_test, self.n = X_test.shape
		
		# initialize Y_predict
		
		Y_predict = np.zeros( self.m_test )
		
		for i in range( self.m_test ) :
			
			x = self.X_test[i]
			
			# find the K nearest neighbors from current test example
			
			neighbors = np.zeros( self.K )
			
			neighbors = self.find_neighbors( x )
			
			# most frequent class in K neighbors
			
			Y_predict[i] = mode( neighbors )[0][0]	
			
		return Y_predict
	
	# Function to find the K nearest neighbors to current test example
			
	def find_neighbors( self, x ) :
		
		# calculate all the euclidean distances between current
		# test example x and training set X_train
		
		euclidean_distances = np.zeros( self.m )
		
		for i in range( self.m ) :
			
			d = self.euclidean( x, self.X_train[i] )
			
			euclidean_distances[i] = d
		
		# sort Y_train according to euclidean_distance_array and
		# store into Y_train_sorted
		
		inds = euclidean_distances.argsort()
		
		Y_train_sorted = self.Y_train[inds]
		
		return Y_train_sorted[:self.K]
	
	# Function to calculate euclidean distance
			
	def euclidean( self, x, x_train ) :
		
		return np.sqrt( np.sum( np.square( x - x_train ) ) )

# Driver code

def main() :
	
	# Importing dataset
	
	df = pd.read_csv( "diabetes.csv" )

	X = df.iloc[:,:-1].values

	Y = df.iloc[:,-1:].values
	
	# Splitting dataset into train and test set

	X_train, X_test, Y_train, Y_test = train_test_split(
	X, Y, test_size = 1/3, random_state = 0 )
	
	# Model training
	
	model = K_Nearest_Neighbors_Classifier( K = 3 )
	
	model.fit( X_train, Y_train )
	
	model1 = KNeighborsClassifier( n_neighbors = 3 )
	
	model1.fit( X_train, Y_train )
	
	# Prediction on test set

	Y_pred = model.predict( X_test )
	
	Y_pred1 = model1.predict( X_test )
	
	# measure performance
	
	correctly_classified = 0
	
	correctly_classified1 = 0
	
	# counter
	
	count = 0
	
	for count in range( np.size( Y_pred ) ) :
		
		if Y_test[count] == Y_pred[count] :
			
			correctly_classified = correctly_classified + 1
		
		if Y_test[count] == Y_pred1[count] :
			
			correctly_classified1 = correctly_classified1 + 1
			
		count = count + 1
		
	print( "Accuracy on test set by our model	 : ", (
	correctly_classified / count ) * 100 )
	print( "Accuracy on test set by sklearn model : ", (
	correctly_classified1 / count ) * 100 )
	
	
if __name__ == "__main__" :
	
	main()

In [160]:
df=pd.read_csv("./diabetes.csv")

In [161]:
x= df.iloc[:,:-1].values
y=df.iloc[:,-1:].values

In [162]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 1/3, random_state = 0 )

In [172]:
def fit(x_train, y_train):
    x_train=x_train
    y_train=y_train
    m,n=x_train.shape
    return m,n
def predict(X_test ) :
    X_test = X_test
    # no_of_test_examples, no_of_features
    m_test,n = X_test.shape    
    y_predict=np.zeros(m_test)
    for i in range(m_test):
        

In [168]:
m,n=fit(X_train,Y_train)

In [188]:
# m_test=X_test.shape[0]
for i in range(m_test):
    new_=X_test[i]
    neighbors = np.zeros(3)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
